# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='channels',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AliBotApp.TelegramUsers'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AliBotApp.TelegramUsers'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AliBotApp.Channels'),
        ),
    ]
