# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AliBotApp', '0002_auto_20171105_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AliBotApp.Channels'),
        ),
    ]
